# Generated by Django 6.0.6 on 2026-06-10 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Предмет",
                "verbose_name_plural": "Предметы",
            },
        ),
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                ("guide", models.URLField(verbose_name="Гайд")),
                (
                    "items",
                    models.ManyToManyField(
                        related_name="quests",
                        to="item_counter.item",
                        verbose_name="Предметы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Квест",
                "verbose_name_plural": "Квесты",
            },
        ),
        migrations.CreateModel(
            name="QuestItemDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_raid", models.PositiveIntegerField(verbose_name="Кол-во в рейде")),
                (
                    "out_raid",
                    models.PositiveIntegerField(verbose_name="Кол-во не в рейде"),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quest_details",
                        to="item_counter.item",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Детали квестового предмета",
                "verbose_name_plural": "Детали квестовых предметов",
            },
        ),
        migrations.CreateModel(
            name="UserItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quest_in_raid",
                    models.PositiveIntegerField(
                        default=0, verbose_name="В рейде для квестов"
                    ),
                ),
                (
                    "quest_out_raid",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Не в рейде для квестов"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="item_counter.item",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="count_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="users",
            field=models.ManyToManyField(
                related_name="items",
                through="item_counter.UserItem",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователи",
            ),
        ),
    ]
