# Generated by Django 6.0.6 on 2026-06-15 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("item_counter", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useritem",
            options={
                "verbose_name": "Собранные предметы пользователя",
                "verbose_name_plural": "Собранные предметы пользователей",
            },
        ),
    ]
