# Generated by Django 6.0.6 on 2026-06-28 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item_counter", "0002_alter_useritem_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="useritem",
            constraint=models.UniqueConstraint(
                fields=("user", "item"), name="unique_user_item"
            ),
        ),
    ]
