# Generated by Django 6.0.6 on 2026-06-30 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item_counter", "0003_useritem_unique_user_item"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["name"], name="item_counte_name_c4cb5d_idx"),
        ),
        migrations.AddIndex(
            model_name="quest",
            index=models.Index(fields=["name"], name="item_counte_name_c303ae_idx"),
        ),
        migrations.AddIndex(
            model_name="useritem",
            index=models.Index(fields=["user"], name="item_counte_user_id_155f7d_idx"),
        ),
        migrations.AddIndex(
            model_name="useritem",
            index=models.Index(fields=["item"], name="item_counte_item_id_d74566_idx"),
        ),
        migrations.AddIndex(
            model_name="useritem",
            index=models.Index(
                fields=["user", "item"], name="item_counte_user_id_51d628_idx"
            ),
        ),
    ]
